site_name: Ứng Dụng Hỗ Trợ Thiên Tai 
site_url: https://fbeta-hou.github.io/FBeta-fulldocs/
repo_url: https://github.com/FBeta-Hou 
repo_name: FBeta_HOU
theme: 
  icon:
    repo: fontawesome/brands/git-alt 
  name: material 
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo-docs.png
  language: vi
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.expand
    - navigation.path
    - navigation.indexes 
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
  palette: 
    #Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: blue
    #Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light blue
      accent: blue 
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true 
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition 
  - pymdownx.details 
copyright: Copyright &copy; 2024 <a href="https://github.com/FBeta-Hou"  target="_blank" rel="noopener">FBeta-Hou</a>