site_name: Ứng Dụng Hỗ Trợ Thiên Tai 
site_url: https://fbeta-hou.github.io/FBeta-fulldocs/
theme: 
  name: material 
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/logo-docs.png
  features:
    - navigation.footer
  palette: 
    #Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: light blue
      accent: blue
    #Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light blue
      accent: blue 
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true 
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition 
  - pymdownx.details 
copyright: Copyright &copy; 2024 <a href="https://github.com/FBeta-Hou"  target="_blank" rel="noopener">FBeta-Hou</a>